#!/usr/bin/env python3

# -*- coding: utf-8 -*-

"""

make_signage.py - derives index-signage.html from the master index.html.

 

The Signage Edition targets Tripleplay/Uniguest Samsung SSSP endpoints: a frozen,

weak, un-updatable Chromium. Everything that engine chokes on is removed:

  - background video never loads (static brand image forced)

  - all backdrop-filter blur removed (opacities bumped to compensate)

  - the 3D coverflow becomes a static crest row (no per-2.6s relayout)

  - the scrolling ticker becomes a stepped headline (one swap per 7s, no 60fps loop)

  - the spotlight flip animation becomes an instant swap

  - the video card is poster-only: no YouTube player script, no ScoreBat iframe

  - full page reload every 30 min (long-running memory hygiene on weak SoCs)

 

House rule: derived editions are REGENERATED from the master by this script after

every master change - never hand-edited. Every transform asserts its anchor and

the script ends with an explicit success marker.

"""

import re, sys, hashlib

 

SRC, OUT = "index.html", "index-signage.html"

html = open(SRC, encoding="utf-8").read()

n_edits = 0

 

def rep(old, new, why):

    global html, n_edits

    assert old in html, "ANCHOR MISSING (%s): %r" % (why, old[:60])

    html = html.replace(old, new)

    n_edits += 1

 

# 1) mark the edition + signage flag for JS branches

rep('"use strict";',

    '"use strict";\nvar SIGNAGE=true; /* Signage Edition - generated by make_signage.py */',

    "signage flag")

 

# 2) background video never loads; brand image is the only background

rep('<video id="bgvid" muted loop autoplay playsinline src="assets/bg.mp4"></video>',

    '<video id="bgvid" muted loop autoplay playsinline></video><!-- signage: no src = never loads; attributes kept for the scanner and the JS refs -->',

    "bg video src stripped")

rep('var BGMODES=["brand","graphic","video"],bgIdx=0;',

    'var BGMODES=["brand"],bgIdx=0; /* signage: static brand background only */',

    "bg modes locked")

 

# 3) remove every backdrop-filter (blur is the #1 GPU killer on SSSP)

before = html.count("backdrop-filter")

html = re.sub(r";?\s*backdrop-filter:[^;}]+;?", ";", html)

html = re.sub(r";?\s*-webkit-backdrop-filter:[^;}]+;?", ";", html)

assert "backdrop-filter" not in html, "blur removal incomplete"

n_edits += 1

# compensate: slightly more opaque glass so text stays readable without blur

rep(".glass{background:linear-gradient(160deg,rgba(0,24,56,0.5),rgba(0,24,56,0.74))",

    ".glass{background:linear-gradient(160deg,rgba(0,24,56,0.68),rgba(0,24,56,0.86))",

    "glass opacity bump")

 

# 4) coverflow: static crest row, no rotation timer, no 3D transforms

rep(" setInterval(function(){cfIdx=(cfIdx+1)%CLUBS.length;layoutCF();},2600);",

    " if(!SIGNAGE)setInterval(function(){cfIdx=(cfIdx+1)%CLUBS.length;layoutCF();},2600);",

    "coverflow timer gated")

rep('  e.style.transform="translate(-50%,-50%) translateX("+(d*78)+"px) translateZ("+(d===0?110:0)+"px) rotateY("+(d*-34)+"deg) scale("+(d===0?1.35:0.95-Math.abs(d)*0.05)+")";',

    '  e.style.transform=SIGNAGE?("translate(-50%,-50%) translateX("+(d*64)+"px) scale("+(d===0?1.1:0.9)+")")'

    ':("translate(-50%,-50%) translateX("+(d*78)+"px) translateZ("+(d===0?110:0)+"px) rotateY("+(d*-34)+"deg) scale("+(d===0?1.35:0.95-Math.abs(d)*0.05)+")");',

    "coverflow flattened")

 

# 5) ticker: stepped headline instead of the 60fps scroll loop

rep("""setInterval(function(){

var line=document.getElementById("tickline");

tickX-=1.4;

if(tickX<-line.offsetWidth)tickX=1920;""",

    """var tickStep=0;

setInterval(function(){

var line=document.getElementById("tickline");

if(SIGNAGE){ /* one headline at a time, swapped every ~7s - no continuous animation */

  if(!NEWS.length)return;

  if(Date.now()%7000<250){tickStep=(tickStep+1)%NEWS.length;}

  line.style.transform="translateY(-50%)";

  line.textContent=NEWS[Math.floor(Date.now()/7000)%NEWS.length];

  return;

}

tickX-=1.4;

if(tickX<-line.offsetWidth)tickX=1920;""",

    "ticker stepped")

 

# 6) spotlight: instant swap, no rotateY flip

rep("""   flipping=true;flipSince=Date.now();

   var card=document.getElementById("spot");

   card.style.transform="rotateY(90deg)";

   setTimeout(function(){""",

    """   flipping=true;flipSince=Date.now();

   var card=document.getElementById("spot");

   if(!SIGNAGE)card.style.transform="rotateY(90deg)";

   setTimeout(function(){""",

    "spot flip gated a")

rep("""    card.style.transform="rotateY(0deg)";

    setTimeout(function(){flipping=false;flipSince=0;},520);

   },510);""",

    """    if(!SIGNAGE)card.style.transform="rotateY(0deg)";

    setTimeout(function(){flipping=false;flipSince=0;},SIGNAGE?20:520);

   },SIGNAGE?20:510);""",

    "spot flip gated b")

 

# 7) video card: poster-only - never load the YouTube player or ScoreBat iframe

rep("""  if(window.YT&&YT.Player){buildYt();}

  else{""",

    """  if(SIGNAGE){showPoster();return;} /* signage: poster only, no player */

  if(window.YT&&YT.Player){buildYt();}

  else{""",

    "video poster-only")

rep("""function tryScorebat(){

/* middle layer: latest City match highlights from ScoreBat (server-fetched) */

if(sbTried){showPoster();return;}""",

    """function tryScorebat(){

if(SIGNAGE){showPoster();return;} /* signage: no cross-origin video iframes */

/* middle layer: latest City match highlights from ScoreBat (server-fetched) */

if(sbTried){showPoster();return;}""",

    "scorebat gated")

 

# 8) memory hygiene: full reload every 30 min

rep('var BOARD_BUILD="b37";',

    'var BOARD_BUILD="b37-signage";\nsetTimeout(function(){location.reload();},30*60*1000);',

    "reload + build id")

 

open(OUT, "w", encoding="utf-8").write(html)

print("SUCCESS MARKER: signage edition generated - %d transforms applied" % n_edits)

print("sha256:", hashlib.sha256(html.encode()).hexdigest()[:16])

assert "backdrop-filter" not in html

assert "SIGNAGE=true" in html

assert 'src="assets/bg.mp4"' not in html

print("post-generation assertions passed")